apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        command: ["/bin/sh", "/scripts/startup.sh"]
        ports:
        - containerPort: 80
        env:
        - name: ENV_TYPE
          valueFrom:
            configMapKeyRef:
              name: nginx-config
              key: ENV_TYPE
        - name: SECRET_VALUE
          valueFrom:
            secretKeyRef:
              name: nginx-secret
              key: secret-value
        volumeMounts:
        - name: nginx-template
          mountPath: /usr/share/nginx/html/index.html.template
          subPath: index.html.template
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
        - name: startup-script
          mountPath: /scripts
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
      volumes:
      - name: nginx-template
        configMap:
          name: nginx-config
          items:
          - key: index.html.template
            path: index.html.template
      - name: nginx-conf
        configMap:
          name: nginx-config
          items:
          - key: nginx.conf
            path: nginx.conf
      - name: startup-script
        configMap:
          name: nginx-config
          items:
          - key: startup.sh
            path: startup.sh
            mode: 0755 
